### ISSUE TITLE
Fix bug with sorting in the GUI

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-utilities-todo#14]
The GUI (to be committed from W14) has three buttons:

* sort by name
* sort by date
* sort by complete

These three buttons have some code behind them, but this code does not work at the moment.   This issue is to find and fix the bug.   This may be a simple fix---finding a bug in the existing code, or it may involve throwing out the code beyond the buttons and starting from scratch.   If its a simple fix, then worth  150 points.  If it ends up being more involved, negotiate with a moderator, TA or instructor to have the point value reassessed.

~estimated 150

**Comment by PazZaitGivon** [comment]
fixed by hanavigil and cpounds
