### ISSUE TITLE
Fix bug with loading from a text file

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-utilities-todo#15]
The GUI has a save feature that saves to a text file.

There is also a "load" feature, but that feature does not work.

Either fix this, or refactor the code so that the save/load feature works on serialized files (like the built in default save/load feature does.)

Depending on the approach taken, this may involve some parsing/regular expression work.  You will need to have some way to notify the user in a "nice" fashion if the text file you are trying to load has invalid syntax (e.g. if it was "saved" by the code, but then hand edited before being loaded back in, and the user that edited it by hand messed up the syntax.)      That might up the point value, so be prepared to renegotiate with your TA/Moderator/Instructor if needed.

~estimated 200

**Comment by PazZaitGivon** [comment]
works as of cpounds and hannavigil
