### ISSUE TITLE
Implement subtasks

### ISSUE THREAD

**Issue by cpounds** [UCSB-CS56-Projects/cs56-utilities-todo#24]
The user should be able to organize their tasks into groups or separate lists. For example a user could create a to-do list relating to school and another one for household chores. 

~estimated 200

**Comment by PazZaitGivon** [comment]
Looks good

**Comment by hannavigil** [comment]
Edit: Estimated ~350 if implementing separate class and reorganizing how tasks/subtasks are displayed.
